---
Logging:
  LogLevel:
    Default: Debug
    Microsoft.Hosting.Lifetime: Information
KRB_SERVICE_ACCOUNT: iwaclient@macsux.com
KRB_PASSWORD: P@ssw0rd
KRB_KDC: dc1.macsux.com
Routes:
  - "http://iwaclient"
#Kestrel:
#  Certificates:
#    Default:
#      Path: "C:\\projects\\KerberosBuildpack\\src\\TapConventionWebhook\\certs\\SteeltoeInstanceCert.pem"
#      KeyPath: "C:\\projects\\KerberosBuildpack\\src\\TapConventionWebhook\\certs\\SteeltoeInstanceKey.pem"
