apiVersion: conventions.apps.tanzu.vmware.com/v1alpha1
kind: ClusterPodConvention
metadata:
  name: kerberos-convention-server
spec:
  webhook:
    clientConfig:
      url: https://kerberos-convention-server.cody.full.tanzu-azure-lab.winterfell.fun/webhook
